### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bwreid** [monoposon/week1#1]
- [index.html, L6](https://github.com/monoposon/week1/blob/master/index.html#L6): Do you mean `stylesheet` here instead of `normalize`?
- [main.css, L98](https://github.com/monoposon/week1/blob/master/styles/main.css#L98): I would include the 0 here (i.e. `0.7rem`);

That's really all I have. You did a really awesome job on this! I would add some comments to your CSS to make it more readable for later.

**Comment by DickinsonMark** [comment]
fixed!
